import type { Meta, StoryObj } from '@storybook/react';
import { UiButtonProps } from "./UiButton.tsx";
declare const meta: Meta<UiButtonProps>;
export default meta;
type Story = StoryObj<UiButtonProps>;
export declare const Primary: Story;
export declare const Clear: Story;
export declare const Outline: Story;
export declare const OutlineXL: Story;
export declare const OutlineDark: Story;
export declare const Background: Story;
export declare const BackgroundInverted: Story;
export declare const Square: Story;
export declare const SquareSizeL: Story;
export declare const SquareSizeM: Story;
export declare const SquareSizeXL: Story;
export declare const Disabled: Story;
